#spring:
#  thymeleaf:
#    cache: false
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html; charset=utf-8
    #    prefix: classpath:/mytemplatess/
#    suffix: .html
server:
  port: 8088 
  servlet:
    context-path: /crud
    
spring:
  messages:
    basename: i18n/login
  thymeleaf:          
    cache: false    #禁用thymleaf模板缓存
#  mvc:
#    date-format: yyyy-MM-dd HH:mm:ss